# Generated by Django 4.2.5 on 2023-09-04 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nations', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('position', models.CharField(max_length=50)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.nationality')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
        ),
    ]
