# Generated by Django 4.2.5 on 2023-09-05 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('nations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('birthdate', models.DateField(verbose_name='Birthdate')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Weight')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.nationality')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['first_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
    ]
