# Generated by Django 4.2.5 on 2023-09-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('cod_nat', models.CharField(max_length=3, verbose_name='Code nation')),
                ('population', models.IntegerField(verbose_name='Population')),
            ],
        ),
    ]
