# Generated by Django 4.2.5 on 2023-09-05 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('num_teams', models.PositiveIntegerField(default=0, verbose_name='Number of teams')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nations.nationality')),
            ],
        ),
    ]
